---
galaxy_info:
  author: Andrew Rothstein
  description: configures an etcd cluster
  company: BlackRock
  license: MIT
  min_ansible_version: "2.0"
  platforms:
    - name: EL
      versions:
        - "7"
        - "8"
    - name: Fedora
      versions:
        - "31"
        - "32"
  galaxy_tags:
    - etcd
    - kv
    - transactions
