---
- name: Collect facts
  ansible.builtin.set_fact:
    cacheable: true
    etcd_listen_public: '{{ "0.0.0.0" if etcd_iface_public == "all" else ansible_default_ipv4.address if etcd_iface_public == "default" else hostvars[inventory_hostname]["ansible_"
      ~ etcd_iface_public]["ipv4"]["address"] }}'
    etcd_listen_cluster: '{{ "0.0.0.0" if etcd_iface_cluster == "all" else ansible_default_ipv4.address if etcd_iface_cluster == "default" else hostvars[inventory_hostname]["ansible_"
      ~ etcd_iface_cluster]["ipv4"]["address"] }}'
    etcd_address_public: '{{ ansible_fqdn if not etcd_use_ips | bool else ansible_default_ipv4.address if etcd_iface_public in [ "all", "default" ] else hostvars[inventory_hostname]["ansible_"
      ~ etcd_iface_public]["ipv4"]["address"] }}'
    etcd_address_cluster: '{{ ansible_fqdn if not etcd_use_ips | bool else ansible_default_ipv4.address if etcd_iface_cluster in [ "all", "default" ] else hostvars[inventory_hostname]["ansible_"
      ~ etcd_iface_cluster]["ipv4"]["address"] }}'

- name: Create etcd group
  become: true
  become_user: root
  ansible.builtin.group:
    name: "{{ etcd_group }}"
    state: present

- name: Create etcd user
  become: true
  become_user: root
  ansible.builtin.user:
    name: "{{ etcd_user }}"
    group: "{{ etcd_group }}"
    home: "{{ etcd_data_dir }}"
    state: present

- name: Create dirs...
  become: true
  become_user: root
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    owner: "{{ etcd_user }}"
    group: "{{ etcd_group }}"
    mode: "0755"
  with_items:
    - /etc/etcd
    - "{{ etcd_cluster_pki_dir }}"

- ansible.builtin.include_tasks: pki.yml
  when: etcd_secure | bool

- name: Install etcd.service configuration
  become: true
  become_user: root
  with_items:
    - f: etcd.conf
      d: /etc/etcd
  ansible.builtin.template:
    src: "{{ item.f }}.j2"
    dest: "{{ item.d }}/{{ item.f }}"
    owner: "{{ etcd_user }}"
    group: "{{ etcd_group }}"
    mode: "0644"
  notify:
    - restart etcd masters
    - restart etcd members

- ansible.builtin.include_tasks: "{{ etcd_init_system }}.yml"
