---
- name: Create cert folders
  ansible.builtin.file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    mode: "0700"
    state: directory
  loop: "{{ chainsmith_folders }}"

- name: Deploy certs
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    mode: "0600"
    content: "{{ item.content }}"
  loop: "{{ chainsmith_files }}"
  loop_control:
    label: "{{ item.dest }}"
