---
# tasks file for chainsmith
- name: Install chainsmith package for easy cert generation
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: "{{ chainsmith_package_state }}"
  loop: "{{ chainsmith_package_names }}"
  run_once: true
  when:
    - ansible_pkg_mgr in ['yum', 'dnf']
