---
- name: Create Minio group
  ansible.builtin.group:
    name: "{{ minio_group }}"
    state: present

- name: Create Minio user
  ansible.builtin.user:
    name: "{{ minio_user }}"
    group: "{{ minio_group }}"
    shell: "/bin/bash"

- name: Create the Minio data storage directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: "0750"
  with_items: "{{ minio_server_datadirs }}"

- name: Install minio packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    disable_gpg_check: "true"
  with_items: "{{ minio_package_names }}"

- name: Generate the Minio server envfile
  ansible.builtin.template:
    src: minio.env.j2
    dest: "{{ minio_server_envfile }}"
    owner: "root"
    group: "{{ minio_group }}"
    mode: "0640"
  notify: restart minio

- name: Create the Minio server systemd config
  ansible.builtin.template:
    src: minio.service.j2
    dest: "/etc/systemd/system/minio.service"
    owner: "root"
    group: "root"
  when: ansible_service_mgr == "systemd"

- name: Create the Minio server init.d config
  ansible.builtin.template:
    src: minio.init.j2
    dest: "/etc/init.d/minio"
    owner: "root"
    group: "root"
    mode: "0750"
  when: ansible_service_mgr != "systemd"
