---
etcd_package_version: present
etcd_package_name: etcd

etcd_user: etcd
etcd_group: etcd
etcd_install_dir: /usr/local/bin
etcd_data_dir: /var/lib/etcd

etcd_master_group_name: etcd_master
etcd_cluster: >
  {%- for host in groups[etcd_master_group_name] -%}
  {{ hostvars[host]['ansible_fqdn'] }}={{ etcd_scheme }}{{ hostvars[host]['etcd_address_cluster'] }}:{{ etcd_port_peer }}{%- if not loop.last -%},{%- endif -%}
  {%- endfor -%}"

etcd_secure: false
etcd_pki_dir: ~/pki-dir
etcd_pki_key_suffix: -key.pem
etcd_pki_cert_suffix: .pem

etcd_use_ips: true
etcd_iface_public: '{{ etcd_network_iface | default("all") }}'
etcd_iface_cluster: '{{ etcd_network_iface | default("default") }}'
etcd_port_client: 2379
etcd_port_peer: 2380

etcd_cluster_name: test-cluster-name
etcd_initial_cluster_token: d8bf8cc6-5158-11e6-8f13-3b32f4935bde

etcd_init_system: systemd
etcd_launch: true

etcd_enable_v2: true # Accept etcd V2 client requests

etcd_additional_envvars: {}
